name: 🚀 Feature Request
description: Suggest a Roboflow Notebooks idea
# title: " "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a Roboflow Notebooks 🚀 Feature Request!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/roboflow-ai/notebooks/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A short description of your tutorial idea.
      placeholder: |
        What tutorial do you think we should add to Roboflow Notebooks?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/roboflow-ai/notebooks/pulls) (PR) to help improve Roboflow Notebooks for everyone, especially if you have a good understanding of how to implement a fix or feature.
        See the Roboflow Notebooks [Contributing Guide](https://github.com/roboflow-ai/notebooks/blob/main/CONTRIBUTING.md) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!